"""Seed content for Typing Racer: real Python idioms, always a single
physical line (both modes type/react to one line at a time -- see
CLAUDE.md). `difficulty` is *not* authored here: `seed.py` computes it from
each line's own symbol density via `difficulty_for()` (difficulty.py), so
the low-Elo end of the bank is mechanically limited to plain alphanumerics
and the high-Elo end is guaranteed to demand real Shift/Caps-Lock density --
that correlation is the whole point of the progressive-overload feel.
"""

SNIPPETS: list[str] = [
    # --- bare minimum: digits, single assignment, no symbols beyond `=` ---
    "x = 1",
    "y = 2",
    "n = 0",
    "total = 0",
    "count = 0",
    "flag = True",
    "value = None",
    "done = False",
    'name = "sam"',
    "print(x)",
    "x = x + 1",
    "i += 1",
    "a = b",
    "nums = []",
    "result = None",
    "z = x + y",
    "items = []",
    "return dp[-1]",
    "stack.append(node)",
    "visited = set()",
    "memo = {}",
    "try:",
    # --- short idioms, low symbol density ---
    "nums = [1, 2, 3, 4, 5]",
    "total = sum(nums)",
    'd = {"a": 1, "b": 2}',
    "x, y = y, x",
    "keys = list(d.keys())",
    "n = int(input())",
    "unique = set(nums)",
    "reversed_list = nums[::-1]",
    "first, *rest = [1, 2, 3, 4]",
    "merged = {**dict1, **dict2}",
    "assert len(nums) > 0",
    "class Solution:",
    "if x > 0 and y < 10:",
    "while left < right:",
    "for i, val in enumerate(nums):",
    "elif isinstance(x, int):",
    "except KeyError as e:",
    "with open(path) as f:",
    "@staticmethod",
    "@classmethod",
    "@property",
    # --- medium: comprehensions, lambdas, f-strings, common APIs ---
    "squares = [x**2 for x in range(10)]",
    "evens = [x for x in nums if x % 2 == 0]",
    "pairs = list(zip(a, b))",
    "sorted_items = sorted(items, key=lambda x: x[1])",
    "result = a if condition else b",
    's = f"{name}: {value:.2f}"',
    "flattened = [x for row in matrix for x in row]",
    "return [i for i, x in enumerate(nums) if x == target]",
    "graph = collections.defaultdict(list)",
    "heapq.heappush(heap, (-freq, num))",
    "q = collections.deque()",
    "count = collections.Counter(words)",
    "nums.sort(key=lambda x: -x)",
    "results = [y for x in data if (y := f(x)) is not None]",
    "@functools.lru_cache(maxsize=None)",
    "def __init__(self, val=0, next=None):",
    "pattern = re.compile(r'\\d+')",
    "data = json.loads(response.text)",
    "self.assertEqual(result, expected)",
    "for key, value in sorted(d.items()):",
    "return max(nums, key=lambda x: x.score)",
    "filtered = list(filter(lambda x: x > 0, nums))",
    "total = functools.reduce(lambda a, b: a + b, nums)",
    "os.path.join(base_dir, 'data', filename)",
    "logging.info('Processed %d items', count)",
    "raise ValueError('invalid input')",
    "return {'id': self.id, 'name': self.name}",
    "def __eq__(self, other): return self.id == other.id",
    # --- hard: type hints, decorators-with-args, dense one-liners ---
    'def fib(n: int) -> int: return n if n <= 1 else fib(n - 1) + fib(n - 2)',
    'config: Optional[Dict[str, Any]] = json.loads(raw) if raw else None',
    'results: dict[str, list[int]] = {k: [v for v in vs if v > 0] for k, vs in data.items()}',
    'matches = [m.group(1) for m in re.finditer(r"(\\w+)=(\\d+)", text)]',
    'handler: Callable[[Request], Response] = lambda req: Response(status=200)',
    'nodes = sorted(graph.nodes(), key=lambda n: (-n.priority, n.id))',
    'mask = (flags & 0xFF) << 8 | (value >> 4)',
    'pattern = re.compile(r"^[A-Za-z0-9_]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")',
    '@dataclass(frozen=True, slots=True)',
    'def __repr__(self) -> str: return f"<{self.__class__.__name__} id={self.id!r}>"',
    'T = TypeVar("T", bound="BaseModel")',
    'self._cache: Dict[Tuple[int, int], float] = {}',
    'assert isinstance(value, (int, float)) and not isinstance(value, bool)',
    'headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}',
    '@functools.wraps(func)',
    'raise ValueError(f"Expected {expected!r}, got {actual!r} instead")',
    'return {**base_config, **overrides, "VERSION": VERSION}',
    'bits = "".join(f"{b:08b}" for b in data)',
    'xs = [x**2 if x % 2 == 0 else -x**2 for x in range(-10, 10)]',
    '@app.route("/users/<int:user_id>", methods=["GET", "POST"])',
    # --- hardest: everything at once -- generics, chained calls, escapes ---
    'items = sorted(((k, v) for k, v in d.items() if v is not None), key=itemgetter(1), reverse=True)',
    'response = {"status": "OK", "data": [x.to_dict() for x in results], "meta": {"count": len(results)}}',
    'query = f"SELECT * FROM {table} WHERE id IN ({\',\'.join(map(str, ids))})"',
    'on_click = lambda e: (e.preventDefault(), self.handle_submit(e))[-1]',
    'self.__dict__.update({k: v for k, v in kwargs.items() if k in self.__slots__})',
    '@retry(exceptions=(ConnectionError, TimeoutError), tries=3, backoff=2)',
    'class Config(BaseModel): model_config = ConfigDict(frozen=True, extra="forbid")',
    'return sorted(candidates, key=lambda c: (-c.score, c.name))[:TOP_K]',
    'URL_PATTERN = re.compile(r"^(https?://)?([\\w.-]+)(:\\d+)?(/.*)?$", re.IGNORECASE)',
    'assert all(isinstance(x, (int, float)) for x in values), f"Bad input: {values!r}"',
    'EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")',
    'SESSION_KEY_RE = re.compile(r"^sess_[A-Za-z0-9]{16}\\.[A-Za-z0-9_-]{20,}$")',
    'REFRESH_TOKEN_RE = re.compile(r"^rt_[A-Za-z0-9]{16}\\.[A-Za-z0-9_-]{24,}$")',
    'AUTH_HEADER_RE = re.compile(r"^Bearer\\s+([A-Za-z0-9\\-_.~+/]+=*)$", re.IGNORECASE)',
    'DEFAULT_HEADERS: Final[Dict[str, str]] = {"X-Request-Id": uuid4().hex}',
]
